### ISSUE TITLE
Epic 0 Требования

### ISSUE THREAD

**Issue by FantasmasDev** [FantasmasDev/PlaylistMaker#29]
- [ ] Проект компилируется и запускается без сбоев и ошибок.

- [ ] Нижняя панель навигации видна при запуске приложения. 

- [ ] Внешний вид панели навигации соответствует дизайну как в светлой, так и в тёмной теме.

- [ ]  Нажатие на табы панели переключает экраны («заглушки») в контейнере.

- [ ] Переход на экран «Команда» осуществляется нажатием на соответствующую вкладку нижней панели навигации.
